
CREATE TABLE [dbo].[RankingGvG](
	[Guild] [varchar](8) NOT NULL,
	[Score] [int] NOT NULL DEFAULT(0),
 CONSTRAINT [PK_RankingGvG] PRIMARY KEY CLUSTERED 
(
	[Guild] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]




